AllCops:
  Exclude:
    - 'examples/**/*'

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 100

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/AmbiguousOperator:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Lint/RedundantSplatExpansion:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Metrics/AbcSize:
  Max: 35

Metrics/BlockLength:
  Exclude:
    - '**/*.gemspec'
    - '**/*_spec.rb'
    - 'lib/apex_charts/helper.rb'

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/ClassLength:
  Max: 350

Metrics/MethodLength:
  Max: 30

Metrics/ModuleLength:
  Max: 200

Naming/MethodParameterName:
  MinNameLength: 2

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/BlockDelimiters:
  Enabled: false

Style/ClassVars:
  Exclude:
    - 'lib/apex_charts/prefixer.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false
